# Generated by Django 4.0.5 on 2022-06-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_alter_goods_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='files/'),
        ),
    ]
