# Generated by Django 4.0.4 on 2022-06-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0006_alter_goods_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='basket',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
