# Generated by Django 4.0.4 on 2022-06-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_alter_goods_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='file',
            field=models.ImageField(upload_to='files/'),
        ),
    ]
